service:
    name: cronJobs

plugins:
    - serverless-webpack

provider:
    name: aws
    runtime: nodejs8.10
    stage: dev
    profile: personal
    region: eu-central-1
    environment:
        modafinilcat__s3__bucket: modafinilcat-notifier
        modafinilcat__s3__object: presentModas.json
        modafinilcat__tg__token: 673982582:AAHdM5iUhDg3YLYmypWdO0I7SW5HCxUgv5Q
        modafinilcat__tg__chatId: https://t.me/ModafinilCatAlerts
    role: arn:aws:iam::072423406874:role/s3-read-write
    timeout: 20

functions:
    check:
        handler: handler.check
        events:
            - schedule:
                rate: rate(1 hour)
